version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  # envf: {}

services:
  postgres:
    image: mooja/postgres:latest
    build: ./compose/postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
     - ./backups:/backups
    # env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: mooja/ssip3_django:latest
    volumes:
      - ./app:/app:ro
      - ./run:/run/gunicorn
      - ./logs:/logs
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    # env_file: .env

  # nginx:
  #   build: ./compose/nginx
  #   depends_on:
  #     - django
  #   ports:
  #     - "0.0.0.0:80:80"

  redis:
    image: redis:3.0
