version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  # envf: {}

services:
  postgres:
    image: mooja/postgres:latest
    build: ./compose/postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
     - ./backups:/backups
    environment:
      - POSTGRES_USER=ssip3

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: mooja/ssip3_django:latest
    volumes:
      - ./app:/app:ro
      - ./run:/run/gunicorn
      - ./logs:/logs
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    environment:
      - POSTGRES_USER=ssip3

  redis:
    image: redis:3.0
