version: '2'

volumes:
  postgres_data: {}
  # postgres_backup: {}
  # envf: {}

services:
  postgres:
    image: postgres:9.5
    # build: ./compose/postgres
    # image: mooja/ssip3_postgres
    volumes:
     - postgres_data:/var/lib/postgresql/data
    #   - postgres_backup:/backups
    # env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    # image: mooja/ssip3_django
    volumes:
      - ./app:/app:ro
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    ports:
      - "0.0.0.0:5000:5000"
    # env_file: .env

  # nginx:
  #   build: ./compose/nginx
  #   depends_on:
  #     - django
  #   ports:
  #     - "0.0.0.0:80:80"

  redis:
    image: redis:3.0
