version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    # image: postgres:9.5
    volumes:
     - ./backups:/backups
    environment:
      - POSTGRES_USER=ssip3

  django:
      # image: mooja/ssip3_django:v01
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=ssip3
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    links:
      - postgres

