# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'News Entries',
            },
        ),
    ]
