# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 14, 0, 24, 11, 524933, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
