# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:43
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsentry',
            options={'verbose_name_plural': 'News Entries'},
        ),
        migrations.RemoveField(
            model_name='newsentry',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='newsentry',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='newsentry',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
    ]
