# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:48
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160427_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsentry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='newsentry',
            name='status_changed',
        ),
        migrations.AddField(
            model_name='newsentry',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='newsentry',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
