# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:30
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160427_1327'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newsentry',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='newsentry',
            name='newstype',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='news', max_length=100, no_check_for_status=True),
        ),
    ]
