# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160427_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
