# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 16:58
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text_format', model_utils.fields.StatusField(choices=[('markdown', 'markdown'), ('raw', 'raw')], default='raw', max_length=100, no_check_for_status=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Flat Pages',
            },
        ),
    ]
