---

# - include: install_additional_packages.yml
#   tags: packages

- include: create_users_and_groups.yml

- include: setup_git_repo.yml
  tags: deploy

- include: setup_docker_service.yml
  tags: docker-service

# - include: setup_django_app.yml
#   tags: deploy

# - include: set_file_permissions.yml
#   tags: deploy
#
- include: setup_supervisor.yml
  tags: supervisor

- include: setup_nginx.yml
  tags: nginx
