---

- name: create extra directory structure
  file: path="{{project_path}}/{{item}}" state=directory mode=0777
  with_items:
    - logs
    - run
    - backups
    - media

- name: copy local .env file
  copy: src=.env dest="{{ project_path}}/app/.env"

- name: pull required images
  command: /usr/local/bin/docker-compose pull
  args:
    chdir: "{{ project_path }}"
  notify: reload supervisor

- name: wait 5 seconds
  pause: seconds=5 

- name: migrate
  command: /usr/local/bin/docker-compose run django python manage.py migrate
  args:
    chdir: "{{ project_path }}"
  notify: reload supervisor
