---

- name: make sure there's a /log directory in the app's root dir
  file: path="{{project_path}}/logs" state=directory mode=0777
  notify: reload nginx

- name: make sure there's a /run directory in the app's root dir
  file: path="{{project_path}}/run" state=directory mode=0777
  notify: reload nginx

- name: make sure there's a /backups directory in the app's root dir
  file: path="{{project_path}}/backups" state=directory mode=0777
  notify: reload nginx

- name: make sure there's a /logs directory in the app's root dir
  file: path="{{project_path}}/logs" state=directory mode=0777
  notify: reload nginx

- name: copy local .env file
  copy: src=.env dest="{{ project_path}}/app/.env"

- name: pull required images
  command: /usr/local/bin/docker-compose pull
  args:
    chdir: "{{ project_path }}"

- name: wait 5 seconds
  pause: seconds=5 

- name: migrate
  command: /usr/local/bin/docker-compose run django python manage.py migrate
  args:
    chdir: "{{ project_path }}"
  notify: restart application
