---

- name: restart application
  supervisorctl: name={{ application_username }} state=restarted

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded
