# vim: sw=2:noai
---
- name: Install Base Packages
  hosts: webapp
  remote_user: root
  become: yes

  roles:

    - base
    - docker
    - role: app
      project_name: "ssip209.org"
      application_username: "ssip209"
      git_repo: "https://github.com/mooja/ssip3"
      git_branch: "master"
